# the version we will use
version: "3"

#only on services
services:
  #our app name
  app:
    build:
      # where to build our images
      context: .
      # the port forward
    ports:
      - "8000:8000"
    # map volume to add the change from host to guest images
    volumes:
      - ./app:/app
    # the command that will run our app -  break the command in next line
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=Test@123
    depends_on: 
      - db
      
  db:
    # postgres lightweight version
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    # set the database variables
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test@123

